on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Dump Image
      run: |
        touch sha.txt
        touch sha2.txt
        sudo tar -C / -c "--exclude=$GITHUB_WORKSPACE" "--exclude=/proc" "--exclude=/dev" "--exclude=/run" "--exclude=/var" usr/bin | tee >(sha256sum > sha.txt) |  gzip -9 -c | tee >(sha256sum > sha2.txt) | tar -zt
        echo "Sha is"
        cat sha.txt
        echo "Sha2 is"
        cat sha2.txt
      shell: bash
