on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    container: ghcr.io/christopherhx/runner-images:runner-latest-no-opt-local
    steps:
    - name: Dump Image
      run: |
        uname -a
        ls -l /bin
        ls -l /usr/bin
      shell: bash
