on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Dump Image
      run: |
        touch sha.txt
        sudo tar -c "--exclude=$GITHUB_WORKSPACE" "--exclude=/proc" "--exclude=/dev" "--exclude=/run" "--exclude=/var" /bin | tee >(sha256sum > sha.txt) | tar -t
        echo "Sha is"
        cat sha.txt
      shell: bash
