on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: Dump Image
      run: |
        curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ github.repository }}/releases -d '{"tag_name":"v0.${{ github.run_id }}.${{ github.run_attempt }}","target_commitish":"main","name":"v0.${{ github.run_id }}.${{ github.run_attempt }}","body":"Dump of runner image","draft":true,"prerelease":false,"generate_release_notes":false}' "--output" resp.json

        cat resp.json
        $releaseid = (cat resp.json | ConvertFrom-Json).id
        echo "release=$releaseid"

        sudo tar -cf "--exclude=$GITHUB_WORKSPACE" "--exclude=/proc" "--exclude=/dev" "--exclude=/run" "--exclude=/var/run" "--exclude=/var/lib/docker" | curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" -H "Content-Type: application/octet-stream" "https://uploads.github.com/repos/${{ github.repository }}/releases/$releaseid/assets?name=image.tar" "--data-binary" "@-"
      shell: pwsh
